const url = 'https://api.covid19india.org/state_district_wise.json'

export const fetchDistricts = async () => {
    try {
        const response = await (await fetch(url)).json();
        const modifiedData = {
            arunachal: [response['Arunachal Pradesh']]
        }
        return modifiedData
    } catch (error) {

    }
}

export const fetchData = async () => {
    try {
        const response = await (await fetch(url)).json();
        // console.log(response)
        const modifiedData =

        {
            //Arunachal
            changlang: [response['Arunachal Pradesh']['districtData']['Changlang']['confirmed']],
            changlangactive: [response['Arunachal Pradesh']['districtData']['Changlang']['active']],
            changlangdeceased: [response['Arunachal Pradesh']['districtData']['Changlang']['deceased']],
            changlangrecovered: [response['Arunachal Pradesh']['districtData']['Changlang']['recovered']],
            lohit: [response['Arunachal Pradesh']['districtData']['Lohit']['confirmed']],
            lohitactive: [response['Arunachal Pradesh']['districtData']['Lohit']['active']],
            lohitdeceased: [response['Arunachal Pradesh']['districtData']['Lohit']['deceased']],
            lohitrecovered: [response['Arunachal Pradesh']['districtData']['Lohit']['recovered']],
            namsai: [response['Arunachal Pradesh']['districtData']['Namsai']['confirmed']],
            namsaiactive: [response['Arunachal Pradesh']['districtData']['Namsai']['active']],
            namsaideceased: [response['Arunachal Pradesh']['districtData']['Namsai']['deceased']],
            namsairecovered: [response['Arunachal Pradesh']['districtData']['Namsai']['recovered']],
            pakke: [response['Arunachal Pradesh']['districtData']['Pakke Kessang']['confirmed']],
            pakkeactive: [response['Arunachal Pradesh']['districtData']['Pakke Kessang']['active']],
            pakkedeceased: [response['Arunachal Pradesh']['districtData']['Pakke Kessang']['deceased']],
            pakkerecovered: [response['Arunachal Pradesh']['districtData']['Pakke Kessang']['recovered']],
            papum: [response['Arunachal Pradesh']['districtData']['Papum Pare']['confirmed']],
            papumactive: [response['Arunachal Pradesh']['districtData']['Papum Pare']['active']],
            papumdeceased: [response['Arunachal Pradesh']['districtData']['Papum Pare']['deceased']],
            papumrecovered: [response['Arunachal Pradesh']['districtData']['Papum Pare']['recovered']],
            tawang: [response['Arunachal Pradesh']['districtData']['Tawang']['confirmed']],
            tawangactive: [response['Arunachal Pradesh']['districtData']['Tawang']['active']],
            tawangdeceased: [response['Arunachal Pradesh']['districtData']['Tawang']['deceased']],
            tawangrecovered: [response['Arunachal Pradesh']['districtData']['Tawang']['recovered']],
            uppersiang: [response['Arunachal Pradesh']['districtData']['Upper Siang']['confirmed']],
            uppersiangactive: [response['Arunachal Pradesh']['districtData']['Upper Siang']['active']],
            uppersiangdeceased: [response['Arunachal Pradesh']['districtData']['Upper Siang']['deceased']],
            uppersiangrecovered: [response['Arunachal Pradesh']['districtData']['Upper Siang']['recovered']],
            westsiang: [response['Arunachal Pradesh']['districtData']['West Siang']['confirmed']],
            westsiangactive: [response['Arunachal Pradesh']['districtData']['West Siang']['active']],
            westsiangdeceased: [response['Arunachal Pradesh']['districtData']['West Siang']['deceased']],
            westsiangrecovered: [response['Arunachal Pradesh']['districtData']['West Siang']['recovered']],
            //Assam
            baksa: [response['Assam']['districtData']['Baksa']['confirmed']],
            baksaactive: [response['Assam']['districtData']['Baksa']['active']],
            baksadeceased: [response['Assam']['districtData']['Baksa']['deceased']],
            baksarecovered: [response['Assam']['districtData']['Baksa']['recovered']],
            barpeta: [response['Assam']['districtData']['Barpeta']['confirmed']],
            barpetaactive: [response['Assam']['districtData']['Barpeta']['active']],
            barpetadeceased: [response['Assam']['districtData']['Barpeta']['deceased']],
            barpetarecovered: [response['Assam']['districtData']['Barpeta']['recovered']],
            biswanath: [response['Assam']['districtData']['Biswanath']['confirmed']],
            biswanathactive: [response['Assam']['districtData']['Biswanath']['active']],
            biswanathdeceased: [response['Assam']['districtData']['Biswanath']['deceased']],
            biswanathrecovered: [response['Assam']['districtData']['Biswanath']['recovered']],
            bongaigaon: [response['Assam']['districtData']['Bongaigaon']['confirmed']],
            bongaigaonactive: [response['Assam']['districtData']['Bongaigaon']['active']],
            bongaigaondeceased: [response['Assam']['districtData']['Bongaigaon']['deceased']],
            bongaigaonrecovered: [response['Assam']['districtData']['Bongaigaon']['recovered']],
            cachar: [response['Assam']['districtData']['Cachar']['confirmed']],
            cacharactive: [response['Assam']['districtData']['Cachar']['active']],
            cachardeceased: [response['Assam']['districtData']['Cachar']['deceased']],
            cacharrecovered: [response['Assam']['districtData']['Cachar']['recovered']],
            charaideo: [response['Assam']['districtData']['Charaideo']['confirmed']],
            charaideoactive: [response['Assam']['districtData']['Charaideo']['active']],
            charaideodeceased: [response['Assam']['districtData']['Charaideo']['deceased']],
            charaideorecovered: [response['Assam']['districtData']['Charaideo']['recovered']],
            chirang: [response['Assam']['districtData']['Chirang']['confirmed']],
            chirangactive: [response['Assam']['districtData']['Chirang']['active']],
            chirangdeceased: [response['Assam']['districtData']['Chirang']['deceased']],
            chirangrecovered: [response['Assam']['districtData']['Chirang']['recovered']],
            darrang: [response['Assam']['districtData']['Darrang']['confirmed']],
            darrangactive: [response['Assam']['districtData']['Darrang']['active']],
            darrangdeceased: [response['Assam']['districtData']['Darrang']['deceased']],
            darrangrecovered: [response['Assam']['districtData']['Darrang']['recovered']],
            dima: [response['Assam']['districtData']['Dima Hasao']['confirmed']],
            dimaactive: [response['Assam']['districtData']['Dima Hasao']['active']],
            dimadeceased: [response['Assam']['districtData']['Dima Hasao']['deceased']],
            dimarecovered: [response['Assam']['districtData']['Dima Hasao']['recovered']],
            dhubri: [response['Assam']['districtData']['Dhubri']['confirmed']],
            dhubriactive: [response['Assam']['districtData']['Dhubri']['active']],
            dhubrideceased: [response['Assam']['districtData']['Dhubri']['deceased']],
            dhubrirecovered: [response['Assam']['districtData']['Dhubri']['recovered']],
            dibrugarh: [response['Assam']['districtData']['Dibrugarh']['confirmed']],
            dibrugarhactive: [response['Assam']['districtData']['Dibrugarh']['active']],
            dibrugarhdeceased: [response['Assam']['districtData']['Dibrugarh']['deceased']],
            dibrugarhrecovered: [response['Assam']['districtData']['Dibrugarh']['recovered']],
            goalpara: [response['Assam']['districtData']['Goalpara']['confirmed']],
            goalparaactive: [response['Assam']['districtData']['Goalpara']['active']],
            goalparadeceased: [response['Assam']['districtData']['Goalpara']['deceased']],
            goalpararecovered: [response['Assam']['districtData']['Goalpara']['recovered']],
            golaghat: [response['Assam']['districtData']['Golaghat']['confirmed']],
            golaghatactive: [response['Assam']['districtData']['Golaghat']['active']],
            golaghatdeceased: [response['Assam']['districtData']['Golaghat']['deceased']],
            golaghatrecovered: [response['Assam']['districtData']['Golaghat']['recovered']],
            hailakandi: [response['Assam']['districtData']['Hailakandi']['confirmed']],
            hailakandiactive: [response['Assam']['districtData']['Hailakandi']['active']],
            hailakandideceased: [response['Assam']['districtData']['Hailakandi']['deceased']],
            hailakandirecovered: [response['Assam']['districtData']['Hailakandi']['recovered']],
            hojai: [response['Assam']['districtData']['Hojai']['confirmed']],
            hojaiactive: [response['Assam']['districtData']['Hojai']['active']],
            hojaideceased: [response['Assam']['districtData']['Hojai']['deceased']],
            hojairecovered: [response['Assam']['districtData']['Hojai']['recovered']],
            jorhat: [response['Assam']['districtData']['Jorhat']['confirmed']],
            jorhatactive: [response['Assam']['districtData']['Jorhat']['active']],
            jorhatdeceased: [response['Assam']['districtData']['Jorhat']['deceased']],
            jorhatrecovered: [response['Assam']['districtData']['Jorhat']['recovered']],
            kamrup: [response['Assam']['districtData']['Kamrup']['confirmed']],
            kamrupactive: [response['Assam']['districtData']['Kamrup']['active']],
            kamrupdeceased: [response['Assam']['districtData']['Kamrup']['deceased']],
            kamruprecovered: [response['Assam']['districtData']['Kamrup']['recovered']],
            kamrupmetro: [response['Assam']['districtData']['Kamrup Metropolitan']['confirmed']],
            kamrupmetroactive: [response['Assam']['districtData']['Kamrup Metropolitan']['active']],
            kamrupmetrodeceased: [response['Assam']['districtData']['Kamrup Metropolitan']['deceased']],
            kamrupmetrorecovered: [response['Assam']['districtData']['Kamrup Metropolitan']['recovered']],
            karimganj: [response['Assam']['districtData']['Karimganj']['confirmed']],
            karimganjactive: [response['Assam']['districtData']['Karimganj']['active']],
            karimganjdeceased: [response['Assam']['districtData']['Karimganj']['deceased']],
            karimganjrecovered: [response['Assam']['districtData']['Karimganj']['recovered']],
            karbianglong: [response['Assam']['districtData']['Karbi Anglong']['confirmed']],
            karbianglongactive: [response['Assam']['districtData']['Karbi Anglong']['active']],
            karbianglongdeceased: [response['Assam']['districtData']['Karbi Anglong']['deceased']],
            karbianglongrecovered: [response['Assam']['districtData']['Karbi Anglong']['recovered']],
            kokrajhar: [response['Assam']['districtData']['Kokrajhar']['confirmed']],
            kokrajharactive: [response['Assam']['districtData']['Kokrajhar']['active']],
            kokrajhardeceased: [response['Assam']['districtData']['Kokrajhar']['deceased']],
            kokrajharrecovered: [response['Assam']['districtData']['Kokrajhar']['recovered']],
            lakhimpur: [response['Assam']['districtData']['Lakhimpur']['confirmed']],
            lakhimpuractive: [response['Assam']['districtData']['Lakhimpur']['active']],
            lakhimpurdeceased: [response['Assam']['districtData']['Lakhimpur']['deceased']],
            lakhimpurrecovered: [response['Assam']['districtData']['Lakhimpur']['recovered']],
            morigaon: [response['Assam']['districtData']['Morigaon']['confirmed']],
            morigaonactive: [response['Assam']['districtData']['Morigaon']['active']],
            morigaondeceased: [response['Assam']['districtData']['Morigaon']['deceased']],
            morigaonrecovered: [response['Assam']['districtData']['Morigaon']['recovered']],
            nagaon: [response['Assam']['districtData']['Nagaon']['confirmed']],
            nagaonactive: [response['Assam']['districtData']['Nagaon']['active']],
            nagaondeceased: [response['Assam']['districtData']['Nagaon']['deceased']],
            nagaonrecovered: [response['Assam']['districtData']['Nagaon']['recovered']],
            nalbari: [response['Assam']['districtData']['Nalbari']['confirmed']],
            nalbariactive: [response['Assam']['districtData']['Nalbari']['active']],
            nalbarideceased: [response['Assam']['districtData']['Nalbari']['deceased']],
            nalbarirecovered: [response['Assam']['districtData']['Nalbari']['recovered']],
            salmara: [response['Assam']['districtData']['South Salmara Mankachar']['confirmed']],
            salmaraactive: [response['Assam']['districtData']['South Salmara Mankachar']['active']],
            salmaradeceased: [response['Assam']['districtData']['South Salmara Mankachar']['deceased']],
            salmararecovered: [response['Assam']['districtData']['South Salmara Mankachar']['recovered']],
            sivasagar: [response['Assam']['districtData']['Sivasagar']['confirmed']],
            sivasagaractive: [response['Assam']['districtData']['Sivasagar']['active']],
            sivasagardeceased: [response['Assam']['districtData']['Sivasagar']['deceased']],
            sivasagarrecovered: [response['Assam']['districtData']['Sivasagar']['recovered']],
            sonitpur: [response['Assam']['districtData']['Sonitpur']['confirmed']],
            sonitpuractive: [response['Assam']['districtData']['Sonitpur']['active']],
            sonitpurdeceased: [response['Assam']['districtData']['Sonitpur']['deceased']],
            sonitpurrecovered: [response['Assam']['districtData']['Sonitpur']['recovered']],
            tinsukia: [response['Assam']['districtData']['Tinsukia']['confirmed']],
            tinsukiaactive: [response['Assam']['districtData']['Tinsukia']['active']],
            tinsukiadeceased: [response['Assam']['districtData']['Tinsukia']['deceased']],
            tinsukiarecovered: [response['Assam']['districtData']['Tinsukia']['recovered']],
            udalguri: [response['Assam']['districtData']['Udalguri']['confirmed']],
            udalguriactive: [response['Assam']['districtData']['Udalguri']['active']],
            udalgurideceased: [response['Assam']['districtData']['Udalguri']['deceased']],
            udalgurirecovered: [response['Assam']['districtData']['Udalguri']['recovered']],
            westkarbi: [response['Assam']['districtData']['West Karbi Anglong']['confirmed']],
            westkarbiactive: [response['Assam']['districtData']['West Karbi Anglong']['active']],
            westkarbideceased: [response['Assam']['districtData']['West Karbi Anglong']['deceased']],
            westkarbirecovered: [response['Assam']['districtData']['West Karbi Anglong']['recovered']],
            unknownassam: [response['Assam']['districtData']['Other State']['confirmed']],
            unknownassamactive: [response['Assam']['districtData']['Other State']['active']],
            unknownassamdeceased: [response['Assam']['districtData']['Other State']['deceased']],
            unknownassamrecovered: [response['Assam']['districtData']['Other State']['recovered']],
            // barpeta: [response['Assam']['districtData']['Barpeta']['confirmed']],
            //Manipur
            bishnupur: [response['Manipur']['districtData']['Bishnupur']['confirmed']],
            bishnupuractive: [response['Manipur']['districtData']['Bishnupur']['active']],
            bishnupurdeceased: [response['Manipur']['districtData']['Bishnupur']['deceased']],
            bishnupurrecovered: [response['Manipur']['districtData']['Bishnupur']['recovered']],
            chandel: [response['Manipur']['districtData']['Chandel']['confirmed']],
            chandelactive: [response['Manipur']['districtData']['Chandel']['active']],
            chandeldeceased: [response['Manipur']['districtData']['Chandel']['deceased']],
            chandelrecovered: [response['Manipur']['districtData']['Chandel']['recovered']],
            churachandpur: [response['Manipur']['districtData']['Churachandpur']['confirmed']],
            churachandpuractive: [response['Manipur']['districtData']['Churachandpur']['active']],
            churachandpurdeceased: [response['Manipur']['districtData']['Churachandpur']['deceased']],
            churachandpurrecovered: [response['Manipur']['districtData']['Churachandpur']['recovered']],
            imphaleast: [response['Manipur']['districtData']['Imphal East']['confirmed']],
            imphaleastactive: [response['Manipur']['districtData']['Imphal East']['active']],
            imphaleastdeceased: [response['Manipur']['districtData']['Imphal East']['deceased']],
            imphaleastrecovered: [response['Manipur']['districtData']['Imphal East']['recovered']],
            imphalwest: [response['Manipur']['districtData']['Imphal West']['confirmed']],
            imphalwestactive: [response['Manipur']['districtData']['Imphal West']['active']],
            imphalwestdeceased: [response['Manipur']['districtData']['Imphal West']['deceased']],
            imphalwestrecovered: [response['Manipur']['districtData']['Imphal West']['recovered']],
            kakching: [response['Manipur']['districtData']['Kakching']['confirmed']],
            kakchingactive: [response['Manipur']['districtData']['Kakching']['active']],
            kakchingdeceased: [response['Manipur']['districtData']['Kakching']['deceased']],
            kakchingrecovered: [response['Manipur']['districtData']['Kakching']['recovered']],
            kamjong: [response['Manipur']['districtData']['Kamjong']['confirmed']],
            kamjongactive: [response['Manipur']['districtData']['Kamjong']['active']],
            kamjongdeceased: [response['Manipur']['districtData']['Kamjong']['deceased']],
            kamjongrecovered: [response['Manipur']['districtData']['Kamjong']['recovered']],
            kangpokpi: [response['Manipur']['districtData']['Kangpokpi']['confirmed']],
            kangpokpiactive: [response['Manipur']['districtData']['Kangpokpi']['active']],
            kangpokpideceased: [response['Manipur']['districtData']['Kangpokpi']['deceased']],
            kangpokpirecovered: [response['Manipur']['districtData']['Kangpokpi']['recovered']],
            noney: [response['Manipur']['districtData']['Noney']['confirmed']],
            noneyactive: [response['Manipur']['districtData']['Noney']['active']],
            noneydeceased: [response['Manipur']['districtData']['Noney']['deceased']],
            noneyrecovered: [response['Manipur']['districtData']['Noney']['recovered']],
            pherzawl: [response['Manipur']['districtData']['Pherzawl']['confirmed']],
            pherzawlactive: [response['Manipur']['districtData']['Pherzawl']['active']],
            pherzawldeceased: [response['Manipur']['districtData']['Pherzawl']['deceased']],
            pherzawlrecovered: [response['Manipur']['districtData']['Pherzawl']['recovered']],
            senapati: [response['Manipur']['districtData']['Senapati']['confirmed']],
            senapatiactive: [response['Manipur']['districtData']['Senapati']['active']],
            senapatideceased: [response['Manipur']['districtData']['Senapati']['deceased']],
            senapatirecovered: [response['Manipur']['districtData']['Senapati']['recovered']],
            tamenglong: [response['Manipur']['districtData']['Tamenglong']['confirmed']],
            tamenglongactive: [response['Manipur']['districtData']['Tamenglong']['active']],
            tamenglongdeceased: [response['Manipur']['districtData']['Tamenglong']['deceased']],
            tamenglongrecovered: [response['Manipur']['districtData']['Tamenglong']['recovered']],
            tengnoupal: [response['Manipur']['districtData']['Tengnoupal']['confirmed']],
            tengnoupalactive: [response['Manipur']['districtData']['Tengnoupal']['active']],
            tengnoupaldeceased: [response['Manipur']['districtData']['Tengnoupal']['deceased']],
            tengnoupalrecovered: [response['Manipur']['districtData']['Tengnoupal']['recovered']],
            thoubal: [response['Manipur']['districtData']['Thoubal']['confirmed']],
            thoubalactive: [response['Manipur']['districtData']['Thoubal']['active']],
            thoubaldeceased: [response['Manipur']['districtData']['Thoubal']['deceased']],
            thoubalrecovered: [response['Manipur']['districtData']['Thoubal']['recovered']],
            ukhrul: [response['Manipur']['districtData']['Ukhrul']['confirmed']],
            ukhrulactive: [response['Manipur']['districtData']['Ukhrul']['active']],
            ukhruldeceased: [response['Manipur']['districtData']['Ukhrul']['deceased']],
            ukhrulrecovered: [response['Manipur']['districtData']['Ukhrul']['recovered']],
            //Meghalaya
            eastkhasi: [response['Meghalaya']['districtData']['East Khasi Hills']['confirmed']],
            eastkhasiactive: [response['Meghalaya']['districtData']['East Khasi Hills']['active']],
            eastkhasideceased: [response['Meghalaya']['districtData']['East Khasi Hills']['deceased']],
            eastkhasirecovered: [response['Meghalaya']['districtData']['East Khasi Hills']['recovered']],
            northgaro: [response['Meghalaya']['districtData']['North Garo Hills']['confirmed']],
            northgaroactive: [response['Meghalaya']['districtData']['North Garo Hills']['active']],
            northgarodeceased: [response['Meghalaya']['districtData']['North Garo Hills']['deceased']],
            northgarorecovered: [response['Meghalaya']['districtData']['North Garo Hills']['recovered']],
            southwestgaro: [response['Meghalaya']['districtData']['South West Garo Hills']['confirmed']],
            southwestgaroactive: [response['Meghalaya']['districtData']['South West Garo Hills']['active']],
            southwestgarodeceased: [response['Meghalaya']['districtData']['South West Garo Hills']['deceased']],
            southwestgarorecovered: [response['Meghalaya']['districtData']['South West Garo Hills']['recovered']],
            westgaro: [response['Meghalaya']['districtData']['West Garo Hills']['confirmed']],
            westgaroactive: [response['Meghalaya']['districtData']['West Garo Hills']['active']],
            westgarodeceased: [response['Meghalaya']['districtData']['West Garo Hills']['deceased']],
            westgarorecovered: [response['Meghalaya']['districtData']['West Garo Hills']['recovered']],
            westjaintia: [response['Meghalaya']['districtData']['West Jaintia Hills']['confirmed']],
            westjaintiaactive: [response['Meghalaya']['districtData']['West Jaintia Hills']['active']],
            westjaintiadeceased: [response['Meghalaya']['districtData']['West Jaintia Hills']['deceased']],
            westjaintiarecovered: [response['Meghalaya']['districtData']['West Jaintia Hills']['recovered']],
            westkhasi: [response['Meghalaya']['districtData']['West Khasi Hills']['confirmed']],
            westkhasiactive: [response['Meghalaya']['districtData']['West Khasi Hills']['active']],
            westkhasideceased: [response['Meghalaya']['districtData']['West Khasi Hills']['deceased']],
            westkhasirecovered: [response['Meghalaya']['districtData']['West Khasi Hills']['recovered']],
            // unknown: [response['Meghalaya']['districtData']['Unknown']['confirmed']],
            // unknownactive: [response['Meghalaya']['districtData']['Unknown']['active']],
            // unknowndeceased: [response['Meghalaya']['districtData']['Unknown']['deceased']],
            // unknownrecovered: [response['Meghalaya']['districtData']['Unknown']['recovered']],
            //Mizoram
            aizawl: [response['Mizoram']['districtData']['Aizawl']['confirmed']],
            aizawlactive: [response['Mizoram']['districtData']['Aizawl']['active']],
            aizawldeceased: [response['Mizoram']['districtData']['Aizawl']['deceased']],
            aizawlrecovered: [response['Mizoram']['districtData']['Aizawl']['recovered']],
            lunglei: [response['Mizoram']['districtData']['Lunglei']['confirmed']],
            lungleiactive: [response['Mizoram']['districtData']['Lunglei']['active']],
            lungleideceased: [response['Mizoram']['districtData']['Lunglei']['deceased']],
            lungleirecovered: [response['Mizoram']['districtData']['Lunglei']['recovered']],
            mamit: [response['Mizoram']['districtData']['Mamit']['confirmed']],
            mamitactive: [response['Mizoram']['districtData']['Mamit']['active']],
            mamitdeceased: [response['Mizoram']['districtData']['Mamit']['deceased']],
            mamitrecovered: [response['Mizoram']['districtData']['Mamit']['recovered']],
            saitual: [response['Mizoram']['districtData']['Saitual']['confirmed']],
            saitualactive: [response['Mizoram']['districtData']['Saitual']['active']],
            saitualdeceased: [response['Mizoram']['districtData']['Saitual']['deceased']],
            saitualrecovered: [response['Mizoram']['districtData']['Saitual']['recovered']],
            serchhip: [response['Mizoram']['districtData']['Serchhip']['confirmed']],
            serchhipactive: [response['Mizoram']['districtData']['Serchhip']['active']],
            serchhipdeceased: [response['Mizoram']['districtData']['Serchhip']['deceased']],
            serchhiprecovered: [response['Mizoram']['districtData']['Serchhip']['recovered']],
            // Nagaland
            dimapur: [response['Nagaland']['districtData']['Dimapur']['confirmed']],
            dimapuractive: [response['Nagaland']['districtData']['Dimapur']['active']],
            dimapurdeceased: [response['Nagaland']['districtData']['Dimapur']['deceased']],
            dimapurrecovered: [response['Nagaland']['districtData']['Dimapur']['recovered']],
            kohima: [response['Nagaland']['districtData']['Kohima']['confirmed']],
            kohimaactive: [response['Nagaland']['districtData']['Kohima']['active']],
            kohimadeceased: [response['Nagaland']['districtData']['Kohima']['deceased']],
            kohimarecovered: [response['Nagaland']['districtData']['Kohima']['recovered']],
            peren: [response['Nagaland']['districtData']['Peren']['confirmed']],
            perenactive: [response['Nagaland']['districtData']['Peren']['active']],
            perendeceased: [response['Nagaland']['districtData']['Peren']['deceased']],
            perenrecovered: [response['Nagaland']['districtData']['Peren']['recovered']],
            tuensang: [response['Nagaland']['districtData']['Tuensang']['confirmed']],
            tuensangactive: [response['Nagaland']['districtData']['Tuensang']['active']],
            tuensangdeceased: [response['Nagaland']['districtData']['Tuensang']['deceased']],
            tuensangrecovered: [response['Nagaland']['districtData']['Tuensang']['recovered']],
            //Sikkim
            eastsikkim: [response['Sikkim']['districtData']['East Sikkim']['confirmed']],
            eastsikkimactive: [response['Sikkim']['districtData']['East Sikkim']['active']],
            eastsikkimdeceased: [response['Sikkim']['districtData']['East Sikkim']['deceased']],
            eastsikkimrecovered: [response['Sikkim']['districtData']['East Sikkim']['recovered']],
            southsikkim: [response['Sikkim']['districtData']['South Sikkim']['confirmed']],
            southsikkimactive: [response['Sikkim']['districtData']['South Sikkim']['active']],
            southsikkimdeceased: [response['Sikkim']['districtData']['South Sikkim']['deceased']],
            southsikkimrecovered: [response['Sikkim']['districtData']['South Sikkim']['recovered']],
            //Tripura
            dhalai: [response['Tripura']['districtData']['Dhalai']['confirmed']],
            dhalaiactive: [response['Tripura']['districtData']['Dhalai']['active']],
            dhalaideceased: [response['Tripura']['districtData']['Dhalai']['deceased']],
            dhalairecovered: [response['Tripura']['districtData']['Dhalai']['recovered']],
            gomati: [response['Tripura']['districtData']['Gomati']['confirmed']],
            gomatiactive: [response['Tripura']['districtData']['Gomati']['active']],
            gomatideceased: [response['Tripura']['districtData']['Gomati']['deceased']],
            gomatirecovered: [response['Tripura']['districtData']['Gomati']['recovered']],
            khowai: [response['Tripura']['districtData']['Khowai']['confirmed']],
            khowaiactive: [response['Tripura']['districtData']['Khowai']['active']],
            khowaideceased: [response['Tripura']['districtData']['Khowai']['deceased']],
            khowairecovered: [response['Tripura']['districtData']['Khowai']['recovered']],
            northtripura: [response['Tripura']['districtData']['North Tripura']['confirmed']],
            northtripuraactive: [response['Tripura']['districtData']['North Tripura']['active']],
            northtripuradeceased: [response['Tripura']['districtData']['North Tripura']['deceased']],
            northtripurarecovered: [response['Tripura']['districtData']['North Tripura']['recovered']],
            sipahijala: [response['Tripura']['districtData']['Sipahijala']['confirmed']],
            sipahijalaactive: [response['Tripura']['districtData']['Sipahijala']['active']],
            sipahijaladeceased: [response['Tripura']['districtData']['Sipahijala']['deceased']],
            sipahijalarecovered: [response['Tripura']['districtData']['Sipahijala']['recovered']],
            southtripura: [response['Tripura']['districtData']['South Tripura']['confirmed']],
            southtripuraactive: [response['Tripura']['districtData']['South Tripura']['active']],
            southtripuradeceased: [response['Tripura']['districtData']['South Tripura']['deceased']],
            southtripurarecovered: [response['Tripura']['districtData']['South Tripura']['recovered']],
            unokoti: [response['Tripura']['districtData']['Unokoti']['confirmed']],
            unokotiactive: [response['Tripura']['districtData']['Unokoti']['active']],
            unokotideceased: [response['Tripura']['districtData']['Unokoti']['deceased']],
            unokotirecovered: [response['Tripura']['districtData']['Unokoti']['recovered']],
            westtripura: [response['Tripura']['districtData']['West Tripura']['confirmed']],
            westtripuraactive: [response['Tripura']['districtData']['West Tripura']['active']],
            westtripuradeceased: [response['Tripura']['districtData']['West Tripura']['deceased']],
            westtripurarecovered: [response['Tripura']['districtData']['West Tripura']['recovered']],
        }
        return modifiedData
    } catch (error) {

    }
}

